### ISSUE TITLE
some inspiration

### ISSUE THREAD

**Issue by MarDiehl** [scivision/fortran-sigwatch#1]
not an issue, but since the repository is empty I wanted to hint at: https://fortran-lang.discourse.group/t/volatile-needed/1648.
This code works for gfortran and ifort.

**Comment by scivision** [comment]
Yes that method segfaults on WSL. Others have written that signal handling on WSL may be less permissive than general Linux since Microsoft rewrote parts of the kernel.

I did fill in the repo now with a library from 2011, that i modified to work on native Windows, WSL and Linux/Unix. I haven't examined all the possibilities yet.

**Comment by MarDiehl** [comment]
thanks for the feedback, good to know that my method does not work on WSL. I'll probably use the method you are using.
